Fix component props type (@hdodov)
Fixes the following error:

Property 'children' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes & Readonly'.

It occurs when you use React 18 and pass children to the <Tooltip> component. Closes #169.

https://github.com/tvkhoa/react-tippy/pull/172